# Run with:
# docker compose up
# Include --build to rebuild the image if there are changes to the Dockerfile or package.json files
# Optionally, use -d to run the app in detached mode

services:
  web:
    image: web:dev
    container_name: ~[ .starter.name ]~-web-dev
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    ports:
      - '4200:4200'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true # To fix an issue with HMR on Windows machines
