name: Production

on:
  push:
    tags:
      - v*.*.*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  actions: read
  contents: read

jobs:
  deploy-web:
    environment:
      name: Production
      url: https://~~_starter.org_name_~~-~~_starter.name_~~.fly.dev
    runs-on: ubuntu-latest
    concurrency: deploy-web
    steps:
      - uses: actions/checkout@v4

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - run: |
          flyctl secrets set VITE_FLAGSMITH_ENVIRONMENT_ID="${{ secrets.VITE_FLAGSMITH_ENVIRONMENT_ID }}"

      - run: |
          flyctl deploy --config apps/web/fly.production.toml --image-label ~~_starter.org_name_~~-~~_starter.name_~~-${{ github.ref_name }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
