name: Production

on:
  push:
    tags:
      - v*.*.*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  actions: read
  contents: read

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy-web:
    environment:
      name: Production
      url: https://evolonix-starter.fly.dev
    runs-on: ubuntu-latest
    concurrency: deploy-web
    steps:
      - uses: actions/checkout@v4

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'

      - run: npm ci --legacy-peer-deps --ignore-scripts

      - run: node customize-ci.js

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - run: |
          flyctl secrets set VITE_FLAGSMITH_ENVIRONMENT_ID="${{ secrets.VITE_FLAGSMITH_ENVIRONMENT_ID }}" --config apps/web/fly.production.toml

      - run: |
          flyctl deploy --config apps/web/fly.production.toml --image-label evolonix-starter-${{ github.ref_name }}
