name: Production

on:
  push:
    tags:
      - v*.*.*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  actions: read
  contents: read

jobs:
  deploy-starter:
    environment:
      name: Production
      url: https://starter.fly.dev
    runs-on: ubuntu-latest
    concurrency: deploy-starter
    steps:
      - uses: actions/checkout@v4

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - run: |
          flyctl deploy --config apps/starter/fly.production.toml --image-label starter-starter-${{ github.ref_name }} \
          --build-arg VITE_FLAGSMITH_ENVIRONMENT_ID="${{ secrets.VITE_FLAGSMITH_ENVIRONMENT_ID }}"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
